spring.application.name=etec_spring04
server.port=8082

# Database Configuration (Injected from .env):
spring.datasource.url=jdbc:postgresql://localhost:5432/etec_springboot04
spring.datasource.username=postgres
spring.datasource.password=123

# JPA/Hibernate Configuration:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File Upload Sizes:
#spring.upload-dir=uploads //For store file in local server
#for upload file use cloudinary, this config is not used
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

#Cloudinary Configuration:
#https://console.cloudinary.com/app/c-c948a1392aadadc99d851c246415e4/home/dashboard
cloudinary.cloud-name=dnuqw4ctr
#https://console.cloudinary.com/app/c-c948a1392aadadc99d851c246415e4/settings/api-keys
cloudinary.api-key=944287327754899
cloudinary.api-secret=RB8hNXZkFL1gCyco0t9KZP7GXkI